name: "Last Green Commit Action"
description: "Get the last green commit on your branch."
author: "Ben Brandt / Talentpair"
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
outputs:
  result:
    description: The sha of the last green commit, or an empty string.
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "check"
  color: "green"
